import argparse
import asyncio
import os
from datetime import datetime
from pathlib import Path

from api import rerank
from api.client import HNClient
from api.fetching import get_best_stories, fetch_story
from api.constants import CANDIDATE_FETCH_COUNT, MAX_USER_STORIES

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HN Rerank | {username}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {{
            darkMode: 'class',
            theme: {{
                extend: {{
                    colors: {{
                        hn: '#ff6600',
                    }}
                }}
            }}
        }}
    </script>
    <style type="text/tailwindcss">
        @layer base {{
            body {{ @apply bg-slate-950 text-slate-200 antialiased; }}
        }}
        .story-card {{ @apply bg-slate-900 border border-slate-800 rounded-xl p-6 transition-all hover:border-hn/50 hover:shadow-lg hover:shadow-hn/5; }}
    </style>
</head>
<body class="p-4 md:p-8">
    <div class="max-w-5xl mx-auto">
        <header class="mb-12 border-b border-slate-800 pb-8 flex flex-col md:flex-row md:items-end justify-between gap-4">
            <div>
                <h1 class="text-4xl font-black text-white tracking-tight mb-2">
                    HN <span class="text-hn">Rerank</span>
                </h1>
                <p class="text-slate-400 font-medium">Personalized for <span class="text-white">@{username}</span></p>
            </div>
            <div class="text-right">
                <p class="text-xs text-slate-500 uppercase tracking-widest font-bold">Last Updated</p>
                <p class="text-sm text-slate-300 font-mono">{timestamp}</p>
            </div>
        </header>

        <div class="grid gap-6">
            {stories_html}
        </div>

        <footer class="mt-20 py-8 border-t border-slate-800 text-center text-slate-500 text-sm">
            Generated by HN Rerank &bull; Local Semantic Analysis
        </footer>
    </div>
</body>
</html>
"""

STORY_CARD_TEMPLATE = """
<div class="story-card group">
    <div class="flex items-start justify-between gap-4 mb-4">
        <div class="flex-1">
            <div class="flex items-center gap-3 mb-2">
                <span class="px-2.5 py-1 rounded-md bg-hn/10 text-hn text-xs font-bold ring-1 ring-inset ring-hn/20">
                    {score}% Match
                </span>
                <span class="text-xs text-slate-500 font-mono">{points} points</span>
            </div>
            <h2 class="text-xl font-bold text-white group-hover:text-hn transition-colors">
                <a href="{url}" target="_blank">{title}</a>
            </h2>
        </div>
        <a href="{hn_url}" target="_blank" class="p-2 rounded-lg bg-slate-800 text-slate-400 hover:bg-hn hover:text-white transition-all shadow-sm" title="View on HN">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2L2 12h3v8h6v-6h2v6h6v-8h3L12 2z"/></svg>
        </a>
    </div>
    
    {reason_html}

    <div class="mt-4 grid gap-2">
        {comments_html}
    </div>
</div>
"""

def generate_story_html(story):
    reason_html = ""
    if story.get('reason'):
        reason_html = f'<p class="text-sm text-emerald-400/90 font-medium mb-4 italic">Matches your interest in: “{story["reason"]}”</p>'
    
    comments_html = ""
    for comment in story.get('comments', [])[:3]:
        snippet = comment[:200] + "..." if len(comment) > 200 else comment
        comments_html += f'<div class="text-sm text-slate-400 bg-slate-950/50 p-3 rounded-lg border border-slate-800/50 italic leading-relaxed">“{snippet}”</div>'

    return STORY_CARD_TEMPLATE.format(
        score=story['match_percent'],
        points=story['points'],
        url=story['url'] or story['hn_url'],
        title=story['title'],
        hn_url=story['hn_url'],
        reason_html=reason_html,
        comments_html=comments_html
    )

async def main():
    parser = argparse.ArgumentParser(description="Generate personalized HN dashboard")
    parser.add_argument("username", help="Hacker News username")
    parser.add_argument("-o", "--output", default="index.html", help="Output file path")
    parser.add_argument("-c", "--count", type=int, default=30, help="Number of stories to show")
    args = parser.parse_args()

    print(f"[*] Building preference profile for @{args.username}...")
    async with HNClient() as hn:
        data = await hn.fetch_user_data(args.username)
        pos_stories = [s for s in await asyncio.gather(*[fetch_story(hn.client, i) for i in list(data["pos"])[:MAX_USER_STORIES]]) if s]
        neg_stories = [s for s in await asyncio.gather(*[fetch_story(hn.client, i) for i in list(data["neg"])[:MAX_USER_STORIES]]) if s]

    if not pos_stories:
        print("[!] No favorites found. Using generic community signals.")
        p_emb = None
    else:
        print(f"[*] Generating embeddings for {len(pos_stories)} favorites...")
        p_emb = rerank.get_embeddings([s["text_content"] for s in pos_stories], is_query=True)

    n_emb = rerank.get_embeddings([s["text_content"] for s in neg_stories], is_query=True) if neg_stories else None
    p_weights = rerank.compute_recency_weights([s["time"] for s in pos_stories]) if pos_stories else None

    print(f"[*] Fetching up to {CANDIDATE_FETCH_COUNT} candidates from Algolia...")
    cands = await get_best_stories(CANDIDATE_FETCH_COUNT, exclude_ids=data["pos"] | data["neg"])
    
    print(f"[*] Reranking {len(cands)} stories...")
    ranked = rerank.rank_stories(cands, p_emb, n_emb, p_weights)

    stories_data = []
    for idx, score, fav_idx in ranked[:args.count]:
        s = cands[idx]
        reason = pos_stories[fav_idx]["title"] if fav_idx != -1 and fav_idx < len(pos_stories) else ""
        stories_data.append({
            "match_percent": int(score * 100),
            "points": s['score'],
            "url": s['url'],
            "title": s['title'],
            "hn_url": f"https://news.ycombinator.com/item?id={s['id']}",
            "reason": reason,
            "comments": s['comments']
        })

    print("[*] Generating HTML...")
    stories_html = "\n".join([generate_story_html(s) for s in stories_data])
    
    final_html = HTML_TEMPLATE.format(
        username=args.username,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        stories_html=stories_html
    )

    Path(args.output).write_text(final_html)
    print(f"[+] Done! Dashboard saved to: {os.path.abspath(args.output)}")

if __name__ == "__main__":
    asyncio.run(main())